# Модуль 8. Практическое задание 8

In [2]:
import requests
import pandas as pd
import numpy as np
import psycopg2

![separator1](https://i.imgur.com/ZUWYTii.png)

## Работа с API

### Получить данные обо всех книгах

In [6]:
api_base_url = 'https://www.anapioficeandfire.com/api'

In [7]:
books_list = requests.get(
    f'{api_base_url}/books?page=1&pageSize=20'
).json()

In [8]:
len(books_list)

12

In [9]:
df_books = pd.DataFrame(books_list)
df_books.head()

,url,name,isbn,authors,numberOfPages,publisher,country,mediaType,released,characters,povCharacters
0,https://www.anapioficeandfire.com/api/books/1,A Game of Thrones,978-0553103540,[George R. R. Martin],694,Bantam Books,United States,Hardcover,1996-08-01T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
1,https://www.anapioficeandfire.com/api/books/2,A Clash of Kings,978-0553108033,[George R. R. Martin],768,Bantam Books,United States,Hardback,1999-02-02T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
2,https://www.anapioficeandfire.com/api/books/3,A Storm of Swords,978-0553106633,[George R. R. Martin],992,Bantam Books,United States,Hardcover,2000-10-31T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
3,https://www.anapioficeandfire.com/api/books/4,The Hedge Knight,978-0976401100,[George R. R. Martin],164,Dabel Brothers Publishing,United States,GraphicNovel,2005-03-09T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
4,https://www.anapioficeandfire.com/api/books/5,A Feast for Crows,978-0553801507,[George R. R. Martin],784,Bantam Books,United Status,Hardcover,2005-11-08T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...

### Получить данные обо всех домах Вестероса

In [11]:
houses_list = []
pagesize = 50

for page in range(1,50):
    response = requests.get(f'{api_base_url}/houses?page={page}&pageSize={pagesize}').json()
    if not response:
        break
    houses_list.extend(response)

In [12]:
len(houses_list)

444

In [13]:
df_houses = pd.DataFrame(houses_list)
df_houses.head()

,url,name,region,coatOfArms,words,titles,seats,currentLord,heir,overlord,founded,founder,diedOut,ancestralWeapons,cadetBranches,swornMembers
0,https://www.anapioficeandfire.com/api/houses/1,House Algood,The Westerlands,"A golden wreath, on a blue field with a gold b...",,[],[],,,https://www.anapioficeandfire.com/api/houses/229,,,,[],[],[]
1,https://www.anapioficeandfire.com/api/houses/2,House Allyrion of Godsgrace,Dorne,"Gyronny Gules and Sable, a hand couped Or",No Foe May Pass,[],[Godsgrace],https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/houses/285,,,,[],[],[https://www.anapioficeandfire.com/api/charact...
2,https://www.anapioficeandfire.com/api/houses/3,House Amber,The North,,,[],[],,,,,,,[],[],[]
3,https://www.anapioficeandfire.com/api/houses/4,House Ambrose,The Reach,"Or, semy of ants gules",Never Resting,[],[],https://www.anapioficeandfire.com/api/characte...,,https://www.anapioficeandfire.com/api/houses/398,,,,[],[],[https://www.anapioficeandfire.com/api/charact...
4,https://www.anapioficeandfire.com/api/houses/5,House Appleton of Appleton,The Reach,"Or, an apple tree eradicated proper fructed gu...",,[],[Appleton],,,https://www.anapioficeandfire.com/api/houses/398,,,,[],[],[]

In [14]:
df_houses.shape

(444, 16)

In [15]:
# в дтатафрейме есть пустые значения, обозначенные [] (в json были пустым списком), заменим их на привычный NaN
df_houses_clean = df_houses.map(lambda x: np.nan if x == [] else x) # map - применяет функцию поэлементно (apply - для строк/столбцов)
df_houses_clean.head(4)

,url,name,region,coatOfArms,words,titles,seats,currentLord,heir,overlord,founded,founder,diedOut,ancestralWeapons,cadetBranches,swornMembers
0,https://www.anapioficeandfire.com/api/houses/1,House Algood,The Westerlands,"A golden wreath, on a blue field with a gold b...",,NaN,NaN,,,https://www.anapioficeandfire.com/api/houses/229,,,,NaN,NaN,NaN
1,https://www.anapioficeandfire.com/api/houses/2,House Allyrion of Godsgrace,Dorne,"Gyronny Gules and Sable, a hand couped Or",No Foe May Pass,NaN,[Godsgrace],https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/houses/285,,,,NaN,NaN,[https://www.anapioficeandfire.com/api/charact...
2,https://www.anapioficeandfire.com/api/houses/3,House Amber,The North,,,NaN,NaN,,,,,,,NaN,NaN,NaN
3,https://www.anapioficeandfire.com/api/houses/4,House Ambrose,The Reach,"Or, semy of ants gules",Never Resting,NaN,NaN,https://www.anapioficeandfire.com/api/characte...,,https://www.anapioficeandfire.com/api/houses/398,,,,NaN,NaN,[https://www.anapioficeandfire.com/api/charact...

In [16]:
df_houses_clean.isna().sum()

url                   0
name                  0
region                0
coatOfArms            0
words                 0
titles              279
seats               209
currentLord           0
heir                  0
overlord              0
founded               0
founder               0
diedOut               0
ancestralWeapons    433
cadetBranches       419
swornMembers        147
dtype: int64

### Получить данные обо всех домах Вестероса, у которых есть девиз

In [18]:
houses_list_with_titles = []
pagesize = 50
parametrs = {'hasTitles' : True} 

for page in range(1,50):
    response_houses = requests.get(
        f'{api_base_url}/houses?page={page}&pageSize={pagesize}',
        params = parametrs
    ).json()
    if not response_houses:
        break
    houses_list_with_titles.extend(response_houses)

In [19]:
len(houses_list_with_titles)

165

In [20]:
df_houses_with_titles = pd.DataFrame(houses_list_with_titles)
df_houses_with_titles_clean = df_houses_with_titles.map(lambda x: np.nan if x == [] else x)
df_houses_with_titles_clean.head()

,url,name,region,coatOfArms,words,titles,seats,currentLord,heir,overlord,founded,founder,diedOut,ancestralWeapons,cadetBranches,swornMembers
0,https://www.anapioficeandfire.com/api/houses/7,House Arryn of the Eyrie,The Vale,A sky-blue falcon soaring against a white moon...,As High as Honor,"[King of Mountain and Vale (formerly), Lord of...","[The Eyrie (summer), Gates of the Moon (winter)]",https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/houses/16,Coming of the Andals,https://www.anapioficeandfire.com/api/characte...,,NaN,[https://www.anapioficeandfire.com/api/houses/6],[https://www.anapioficeandfire.com/api/charact...
1,https://www.anapioficeandfire.com/api/houses/8,House Ashford of Ashford,The Reach,"Tenny, a sun in splendour beneath a chevron in...",Our Sun Shines Bright,[Lord of Ashford],[Ashford],,,https://www.anapioficeandfire.com/api/houses/398,,,,NaN,NaN,[https://www.anapioficeandfire.com/api/charact...
2,https://www.anapioficeandfire.com/api/houses/10,House Baelish of Harrenhal,The Riverlands,"A field of silver mockingbirds, on a green fie...",,"[Lord Paramount of the Trident, Lord of Harren...",[Harrenhal],https://www.anapioficeandfire.com/api/characte...,,https://www.anapioficeandfire.com/api/houses/16,299 AC,https://www.anapioficeandfire.com/api/characte...,,NaN,NaN,[https://www.anapioficeandfire.com/api/charact...
3,https://www.anapioficeandfire.com/api/houses/13,House Banefort of Banefort,The Westerlands,"A black hooded man, on a grey field, within a ...",,[Lord of Banefort],[Banefort],https://www.anapioficeandfire.com/api/characte...,,https://www.anapioficeandfire.com/api/houses/229,,https://www.anapioficeandfire.com/api/characte...,,NaN,NaN,[https://www.anapioficeandfire.com/api/charact...
4,https://www.anapioficeandfire.com/api/houses/14,House Bar Emmon of Sharp Point,The Crownlands,"Fretty argent and white, a swordfish embowed h...",,[Lord of Sharp Point],[Sharp Point],https://www.anapioficeandfire.com/api/characte...,,https://www.anapioficeandfire.com/api/houses/15,,,,NaN,NaN,[https://www.anapioficeandfire.com/api/charact...

In [21]:
df_houses_with_titles.shape

(165, 16)

In [22]:
df_houses_with_titles_clean.isna().sum()

url                   0
name                  0
region                0
coatOfArms            0
words                 0
titles                0
seats                23
currentLord           0
heir                  0
overlord              0
founded               0
founder               0
diedOut               0
ancestralWeapons    156
cadetBranches       146
swornMembers         17
dtype: int64

![separator1](https://i.imgur.com/ZUWYTii.png)

## Работа с БД

In [25]:
conn_string = "host='hh-pgsql-public.ebi.ac.uk' dbname='pfmegrnargs' user='reader' password='NWDMCE5xdipIjRrp'"
conn = psycopg2.connect(conn_string) # подключаемся к БД

### Получить 10 строк из таблицы rnc_database

In [27]:
with conn.cursor() as cursor:
    cursor.execute('SELECT * FROM rnc_database LIMIT 10')
    rnc_10 = cursor.fetchall() #fetchall возвращает строки
    # Возвращаем имена столбцов
    column_names = [desc[0] for desc in cursor.description] #cursor.description возвращает список кортежей, описывающих столбцы в наборе результатов (0 элемент - название столбца)

In [28]:
rnc_10[0]

(1,
 datetime.datetime(2017, 5, 1, 0, 0),
 'RNACEN',
 'ENA',
 884,
 'ENA',
 'Y',
 ' ',
 'ENA',
 '',
 412,
 10,
 900074,
 12086180,
 814855,
 "provides a comprehensive record of the world's nucleotide sequencing information",
 'https://www.ebi.ac.uk/ena/browser/',
 [{'upi': 'URS00002D0E0C', 'taxid': 10090},
  {'upi': 'URS000035EE7E', 'taxid': 9606},
  {'upi': 'URS0000000001', 'taxid': 77133}],
 [{'title': 'The European Nucleotide Archive in 2017',
   'authors': 'Silvester et al.',
   'journal': 'Nucleic Acids Res. 2017',
   'pubmed_id': '29140475'}])

In [29]:
rnс_df = pd.DataFrame(rnc_10, columns = column_names)
rnс_df.head()

,id,timestamp,userstamp,descr,current_release,full_descr,alive,for_release,display_name,project_id,avg_length,min_length,max_length,num_sequences,num_organisms,description,url,example,reference
0,1,2017-05-01 00:00:00.000000,RNACEN,ENA,884,ENA,Y,,ENA,,412.0,10.0,900074.0,12086180,814855,provides a comprehensive record of the world's...,https://www.ebi.ac.uk/ena/browser/,"[{'upi': 'URS00002D0E0C', 'taxid': 10090}, {'u...",[{'title': 'The European Nucleotide Archive in...
1,5,2017-05-17 00:00:00.000000,RNACEN,VEGA,98,VEGA,N,,VEGA,PRJEB4568,NaN,NaN,NaN,0,0,is a repository for high-quality gene models p...,http://vega.sanger.ac.uk/,"[{'upi': 'URS00000B15DA', 'taxid': 9606}, {'up...",[{'title': 'The GENCODE v7 catalog of human lo...
2,26,2017-05-01 00:00:00.000000,RNACEN,GENCODE,450,GENCODE,N,,GENCODE,,889.0,32.0,205012.0,47677,2,produces high quality reference gene annotatio...,http://gencodegenes.org/,"[{'upi': 'URS00000B15DA', 'taxid': 9606}, {'up...",[{'title': 'GENCODE: the reference human genom...
3,55,2023-10-10 15:02:45.191606,RNACEN,MGNIFY,839,MGnify,Y,None,MGnify,None,151.0,27.0,3514.0,135924,1929,None,None,None,None
4,41,2017-05-01 00:00:00.000000,RNACEN,GENECARDS,867,MalaCards,Y,,GeneCards,,1298.0,16.0,347561.0,517673,1,"is a searchable, integrative database that pro...",https://www.genecards.org/,"[{'upi': 'URS0000EBFCE3', 'taxid': 9606}, {'up...",[{'title': 'The GeneCards Suite: From Gene Dat...

In [30]:
rnс_df.shape

(10, 19)

### Получить значения столбцов display_name, num_sequences, num_organisms, url для 10 строк из таблицы rnc_database

In [32]:
with conn.cursor() as cursor:
    cursor.execute('SELECT display_name, num_sequences, num_organisms, url FROM rnc_database LIMIT 10')
    rnc_10_data = cursor.fetchall()
    columns = [desc[0] for desc in cursor.description]

In [33]:
rnc_10_data[0]

('ENA', 12086180, 814855, 'https://www.ebi.ac.uk/ena/browser/')

In [34]:
rnc_10_df = pd.DataFrame(rnc_10_data, columns = columns)
rnc_10_df.head()

,display_name,num_sequences,num_organisms,url
0,ENA,12086180,814855,https://www.ebi.ac.uk/ena/browser/
1,VEGA,0,0,http://vega.sanger.ac.uk/
2,GENCODE,47677,2,http://gencodegenes.org/
3,MGnify,135924,1929,None
4,GeneCards,517673,1,https://www.genecards.org/

In [35]:
rnc_10_df.shape

(10, 4)